// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeDpXb84IvGS-KlQFtYEp6b2Pki3sYXFs',
    appId: '1:21021837446:web:0daafb4433badc6914e907',
    messagingSenderId: '21021837446',
    projectId: 'chatting-app-73f24',
    authDomain: 'chatting-app-73f24.firebaseapp.com',
    storageBucket: 'chatting-app-73f24.appspot.com',
    measurementId: 'G-R4NV971L46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwU0wtpdTV89_2bfV_FoxrGRkjtbG4AIk',
    appId: '1:21021837446:android:f19a9621f93d247f14e907',
    messagingSenderId: '21021837446',
    projectId: 'chatting-app-73f24',
    storageBucket: 'chatting-app-73f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgSCNxDSD8t-Qs-F1uh29nnl_hPGnd05c',
    appId: '1:21021837446:ios:3de74efc991b858e14e907',
    messagingSenderId: '21021837446',
    projectId: 'chatting-app-73f24',
    storageBucket: 'chatting-app-73f24.appspot.com',
    iosBundleId: 'com.example.versionone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgSCNxDSD8t-Qs-F1uh29nnl_hPGnd05c',
    appId: '1:21021837446:ios:03f1363a41026d9414e907',
    messagingSenderId: '21021837446',
    projectId: 'chatting-app-73f24',
    storageBucket: 'chatting-app-73f24.appspot.com',
    iosBundleId: 'com.example.versionone.RunnerTests',
  );
}
